### ISSUE TITLE
Comparing mycorrhizal biomass between treatments

### ISSUE THREAD

**Issue by bpbond** [R-gon18/suli-tempestx#2]
Hi @ahopple

@R-gon18 had a good question about [Moyano et al. 2007](http://dx.doi.org/10.1016/j.soilbio.2006.10.001): shouldn't they have measured mycorrhizal biomass in the 35 µm and control cores? That is, how do we know that excluding roots didn't also exclude some root-associated fungi?

Something to think about for TEMPESTX!

**Comment by ahopple** [comment]
@bpbond - yes, they absolutely should have measured mycorrhizal biomass in all samples. Although, my guess is that excluding roots will have little impact on mycorrhizal biomass - mycorrhizae are so ubiquitous in soils, they are essentially the fibers woven together to form the existing three-dimensional soil "carpet" in forests. While our trenching may have reduced their abundance since they were also severed, they should have no problem penetrating the 45 um mesh and re-establishing themselves. We will probably also have quite a bit of mycorrhizae in the 1 um treatment since they are so pervasive, but my hope is that the 1 um barrier will at least reduce their biomass to a point that it is reflected in the soil carbon cycle. Nice catch, @R-gon18!
